config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'accounts'

  root 'homes#index'

  resources :homes do
    collection do
      get 'about_us'
      get 'history'
    end
  end 

  resources :users

end

app/models/contact_information.rb
class ContactInformation < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, 
    :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  has_one :contact_information
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_filter :authenticate_user!, :only => [:history]
  
  def index
  end

  def about_us
  end

  def history
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  before_filter :authenticate_user!
  before_action :prepare_user, :only => [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to user_path(id: @user.id), notice: "User data has been updated"
    else
      redirect_to user_path(id: @user.id), alert: "User data failed to update"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end

  def contact_information_params
    params.require(:contact_information).permit(:baptist_number, :gender, :birthday, :address, :postal_code, :phone, :job_description, :website)
  end

  def prepare_user
    @user = User.where(id: params[:id]).first

    if @user.blank?
      redirect_to root_path, :alert => "User not found"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_class_active(controller, action)
    if params[:controller] == controller && params[:action] == action
      return true
    else
      return false
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
  def popover_history_button(year, placement, title, content)
    button_tag year, :class => "btn btn-default history_button", 
      "data-container" => "body", 
      'data-toggle' => "popover", 
      "data-placement" => placement, 
      "title" => title, 
      "data-content" => content
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about_us.html.erb
<div class="jumbotron transparent">
  <div class="container">
    <h1><small>Gereja Baptis Indonesia</small> Baitlahim <small>Bandung</small></h1>
    <p>
      Selamat datang di halaman tentang kami, Gereja Baptis Indonesia Baitlahim Bandung.. Pada halaman ini menjelaskan secara singkat siapa dan berawal dari mana Gereja kami..
    </p>
  </div>
</div>
<div class="container">
  <p class="text-justify lead">
    <strong>Gereja Baptis Indonesia Baitlahim Bandung</strong> dimulai pada tahun 1954 di rumah anggota Gereja Baptis Pertama Bandung, Diakon Mathias. Pelayanan di mulai dengan pelayanan Sekolah Minggu di Jl. Jendral Sudirman oleh Bapak dan Ibu Diakon Mathias bersama beberapa orang guru Sekolah Minggu dari Gereja Baptis Pertama Bandung. Kehadiran Sekolah Minggu pada saat itu di hadiri rata-rata 40 orang anak. Pelayanan ini terus berkembang pesat sehingga membuat tempat pelayanan tidak mencukupi lagi.
  </p>
  <p class="text-justify lead">
    Puji Tuhan, ketika Gereja bergumul untuk mencari tempat pelayanan baru, keluarga <strong>Widarma</strong> yang tinggal dekat rumah Diakon Mathias merelakan rumahnya digunakan untuk pelayanan sekolah minggu. Dan selanjutnya seluruh kegiatan dialihkan ke <strong>tempat yang baru</strong>. Di tempat ini kebaktian diadakan pagi dan sore hari. Selain Sekolah Minggu, diadakan juga kegiatan <big><strong>Persatuan Latihan</strong></big> untuk <strong>Kaum Muda</strong> dan <strong>Persekutuan Wanita</strong>.
  </p>
  <p class="text-justify lead">
    Pada <big>4 Maret 1962</big>, <strong>Pdt. Ishak Iskandar</strong> dengan 25 anggota gereja bertekad mengorganisasikan diri dengan nama <strong><big>"Gereja Baptis Raya Barat"</big></strong>. Dengan dasar ayat, Markus 16:15 <small><em>"Pergilah ke seluruh dunia beritakanlah Injil kepada segala makhluk"</em></small>. Pada masa itu <strong>Miss Ditsworth</strong> dari misi baptis juga terlibat melayani.
  </p>
  <p class="text-justify lead">
    Pada <big>Juli 1965</big> Pdt Ishak Iskandar terpanggil melayani di tempat lain dan <strong>Pdt. Daniel Marantika</strong> yang menjadi Gembala Sidang menggantikan beliau. Ada beberapa peristiwa penting yang patut dicatat semasa Pdt Daniel Marantika menjabat sebagai Gembala Sidang, yaitu:
  </p>

  <blockquote class="blockquote-reverse">
    <ol>
      <li>
        Tahun 1966 perubahan nama Gereja Raya Barat menjadi <strong><big>"Gereja Baptis Baitlahim"</big></strong> yang berarti <em>gudang gandum</em>.
      </li>
      <li>
        Dibuka dua cabang gereja yaitu di Jl. Natawijaya (rumah diakon Harun Slamet) dan di Gang Beureum.
        <footer>Sayangnya cabang Gang Beureum berakhir tahun 1972</footer>
      </li>
      <li>
        Tahun 1967 cabang Natawijaya mengorganisasikan diri dan bernama <strong><big>"Gereja Baptis Indonesia Immanuel"</big></strong>.
      </li>
      <li>
        Tahun 1967 gereja turut mengsukseskan <big>GEHIBA</big> atau <big>Gerakan Hidup Baru</big> yaitu suatu kebangunan rohani tingkat nasional.
      </li>
      <li>
        Pada tahun 1968 pelayanan berjalan terus dan berkembang sehingga pada masa itu ada <big>154</big> orang anggota gereja.
      </li>
    </ol>
  </blockquote>
</div>

app/views/homes/history.html.erb
<script type="text/javascript">
  $(function() {
    $(".history_button").popover({ animation: true, trigger: 'click' })
  });
</script>

<div class="jumbotron transparent">
  <div class="container">
    <h1>Sejarah <small>Gereja Baptis Indonesia</small> Baitlahim <small>Bandung</small></h1>
    <p>
      Selamat datang di halaman sejarah tentang kami, Gereja Baptis Indonesia Baitlahim Bandung.. Pada halaman ini menjabarkan sejarah tentang siapa dan berawal dari mana Gereja kami..
    </p>
  </div>
</div>

<%
  content1 = 'Gereja Baptis Indonesia Baitlahim Bandung dimulai pada tahun 1954 di rumah anggota Gereja Baptis Pertama Bandung, Diakon Mathias. Pelayanan di mulai dengan pelayanan Sekolah Minggu di Jl. Jendral Sudirman oleh Bapak dan Ibu Diakon Mathias bersama beberapa orang guru Sekolah Minggu dari Gereja Baptis Pertama Bandung. Kehadiran Sekolah Minggu pada saat itu di hadiri rata-rata 40 orang anak. Keluarga Widarma yang tinggal dekat rumah Diakon Mathias merelakan rumahnya digunakan untuk pelayanan sekolah minggu. Dan selanjutnya seluruh kegiatan dialihkan ke tempat yang baru. Di tempat ini kebaktian diadakan pagi dan sore hari. Selain Sekolah Minggu, diadakan juga kegiatan Persatuan Latihan untuk Kaum Muda dan Persekutuan Wanita. '

  content2 = 'Pdt. Ishak Iskandar dengan 25 anggota gereja bertekad mengorganisasikan diri dengan nama "Gereja Baptis Raya Barat". Dengan dasar ayat, Markus 16:15 "Pergilah ke seluruh dunia beritakanlah Injil kepada segala makhluk". Pada masa itu Miss Ditsworth dari misi baptis juga terlibat melayani. '

  content3 = 'Pada Juli 1965 Pdt Ishak Iskandar terpanggil melayani di tempat lain dan Pdt. Daniel Marantika yang menjadi Gembala Sidang menggantikan beliau.'

  content4 = 'Tahun 1966 perubahan nama Gereja Raya Barat menjadi "Gereja Baptis Baitlahim" yang berarti gudang gandum.'

  content5 = 'Dibuka dua cabang gereja yaitu di Jl. Natawijaya (rumah diakon Harun Slamet) dan di Gang Beureum.'

  content6 = 'Tahun 1967 cabang Natawijaya mengorganisasikan diri dan bernama "Gereja Baptis Indonesia Immanuel".'

  content7 = 'Tahun 1967 gereja turut mengsukseskan GEHIBA atau Gerakan Hidup Baru yaitu suatu kebangunan rohani tingkat nasional.'

  content8 = 'Pada tahun 1968 pelayanan berjalan terus dan berkembang sehingga pada masa itu ada 154 orang anggota gereja.'
%>

<div class="container text-center">
  <%= popover_history_button('1954', 'left', '1954', content1) %><br/><br/>
  <%= popover_history_button('1962', 'right', '14 Maret 1962', content2) %><br/><br/>
  <%= popover_history_button('1965', 'left', 'Juli 1965', content3) %><br/><br/>
  <%= popover_history_button('1966', 'right', '1966', content4) %><br/><br/>
  <%= popover_history_button('1966', 'left', '1966', content5) %><br/><br/>
  <%= popover_history_button('1967', 'right', '1967', content6) %><br/><br/>
  <%= popover_history_button('1967', 'left', '1967', content7) %><br/><br/>
  <%= popover_history_button('1968', 'right', '1968', content8) %><br/><br/>
</div>

app/views/homes/index.html.erb
<div class="jumbotron transparent">
	<div class="container">
	  <h1>Welcome <small>to our site</small></h1>
	  <p><big>Gereja Baptis Indonesia Baitlahim Bandung</big> dimulai pada tahun 1954 di rumah anggota Gereja Baptis Pertama Bandung, Diakon Mathias..</p>

		<!-- Button trigger modal -->
	  <p><a class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Show more</a></p>
	  
		<!-- Modal -->
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		        <h3 class="modal-title" id="myModalLabel">Gereja Baptis Indonesia Baitlahim Bandung</h3>
		      </div>
		      <div class="modal-body">
		      	<p class="text-justify lead"><strong>Gereja Baptis Indonesia Baitlahim Bandung</strong> dimulai pada tahun 1954 di rumah anggota Gereja Baptis Pertama Bandung, Diakon Mathias. Pelayanan di mulai dengan pelayanan Sekolah Minggu di Jl. Jendral Sudirman oleh Bapak dan Ibu Diakon Mathias bersama beberapa orang guru Sekolah Minggu dari Gereja Baptis Pertama Bandung. Kehadiran Sekolah Minggu pada saat itu di hadiri rata-rata 40 orang anak. Pelayanan ini terus berkembang pesat sehingga membuat tempat pelayanan tidak mencukupi lagi.</p>
		      </div>
		      <div class="modal-footer">
		        <%= link_to "About us", about_us_homes_path, :class => "btn btn-primary" %>
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		      </div>
		    </div>
		  </div>
		</div>
	</div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation_links.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo_sss.png'), root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if check_class_active('homes', 'about_us') %>"><%= link_to "About Us", about_us_homes_path %></li>
        <li class="<%= 'active' if check_class_active('homes', 'contact_us') %>"><a href="#">Contact Us</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Baitlahim <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Schedules</a></li>
            <li><a href="#">Church officials</a></li>
            <li class="divider"></li>
            <li><a href="#">Vision</a></li>
            <li><a href="#">Mission</a></li>
            <li class="divider"></li>
            <li><%= link_to "History", history_homes_path %></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.first_name.present? ? current_user.first_name : "Hi, Please fill your contact information here" %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "My Profile", user_path(id: current_user.id) %>
              </li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="<%= destroy_user_session_url %>" data-method="delete"><span class='glyphicon glyphicon-off red'></span> Log Out</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	  <title>Baitlahim</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <link rel="shortcut icon" href="../assets/favicon.png">
	</head>
	<body>
		<%= render 'layouts/navigation_links' %>
	  <%= render 'layouts/messages' %>
		<%= yield %>

	</body>
</html>

app/views/users/edit.html.erb
<div class="jumbotron transparent">
  <div class="container">
    <h1><small>Update Contact Information</small></h1>
    <p>
      Please enter your valid contact information to our website..
      <br/>
      If you have problems, please contact our administrator..
    </p>
  </div>
</div>

<div class="container">
  <%= form_for @user, url: user_path, method: :patch, html: { :class => 'form-horizontal' } do |f| %>
    <div class="form-group">
      <%= f.label :first_name, :class => "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <%= f.text_field :first_name, autofocus: true, :class => "form-control", :placeholder => "Enter your first name" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :last_name, :class => "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <%= f.text_field :last_name, autocomplete: "off", :class => "form-control", :placeholder => "Enter your last name" %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag "baptist_number", "Baptist Number", :class => "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <%= text_field_tag "contact_information[baptist_number]", (@user.contact_information.baptist_number rescue ""), :class => "form-control", :placeholder => "Enter your baptist number" %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag "gender", "Gender", :class => "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <div class="input-group">
          <span class="input-group-addon">
            <input type="radio">
          </span>
          <input type="text" class="form-control">
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-8">
        <%= f.submit "Update", :class => "btn btn-default btn-lg" %>
      </div>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="jumbotron transparent">
  <div class="container">
    <h1><small>Contact Information</small></h1>
    <p>
      Selamat datang di halaman tentang kami, Gereja Baptis Indonesia Baitlahim Bandung.. Pada halaman ini menjelaskan secara singkat siapa dan berawal dari mana Gereja kami..
    </p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <%= label_tag "first_name", "First name", :class => "control-label" %>
    </div>
    <div class="col-md-8">
      <%= label_tag "first_name", (@user.first_name.present? ? @user.first_name : "Please fill your contact information") %>
    </div>
    <div class="col-md-1">
      <%= link_to edit_user_path(id: @user.id) do %>
        <span class='glyphicon glyphicon-pencil'></span> Edit
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= label_tag "last_name", "Last name", :class => "control-label" %>
    </div>
    <div class="col-md-8">
      <%= label_tag "last_name", @user.last_name.present? ? @user.last_name : "" %>
    </div>
  </div>

  <% if @user.contact_information %>
    <div class="row">
      <div class="col-md-2">
        <%= label_tag "baptist_number", "Baptist number", :class => "control-label" %>
      <div class="col-md-8">
        <%= label_tag "baptist_number", @user.baptist_number %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= label_tag "birthday", "Birthday", :class => "control-label" %>
      </div>
      <div class="col-md-8">
        <%= label_tag "birthday", @user.contact_information.birthday %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= label_tag "address", "Address", :class => "control-label" %>
      </div>
      <div class="col-md-8">
        <%= label_tag "address", @user.contact_information.address %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= label_tag "postal_code", "Postal code", :class => "control-label" %>
      </div>
      <div class="col-md-8">
        <%= label_tag "postal_code", @user.contact_information.postal_code %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= label_tag "phone", "Phone", :class => "control-label" %>
      </div>
      <div class="col-md-8">
        <%= label_tag "phone", @user.contact_information.phone %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= label_tag "gender", "Gender", :class => "control-label" %>
      </div>
      <div class="col-md-8">
        <%= label_tag "gender", @user.contact_information.gender %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= label_tag "job_description", "Jobs", :class => "control-label" %>
      </div>
      <div class="col-md-8">
        <%= label_tag "job_description", @user.contact_information.job_description %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= label_tag "website", "Website", :class => "control-label" %>
      </div>
      <div class="col-md-8">
        <%= label_tag "website", @user.contact_information.website %>
      </div>
    </div>
  <% end %>
</div>